### ISSUE TITLE
TypeError: Cannot destructure property 'id' of 'nh(...)' as it is undefined

### ISSUE THREAD

**Issue by mattiagalati** [udima-university/moodle-mod_jitsi#88]
Greetings,
from a couple of days, when I click the access button and the new window opens, I cannot see the usual form to join the meeting and the page remains completely empty.
If I refresh the page or use again the button several times (like 7 or 8 times), it works again like always.
Opening the Chrome Developer Tools, when the error occurs, I can see the following exceptions:

```
conference.js:3109 Uncaught (in promise) TypeError: Cannot destructure property 'id' of 'nh(...)' as it is undefined.
    at Object.changeLocalDisplayName (conference.js:3109:17)
    at Object.display-name (API.js:169:28)
    at API.js:617:22
    at Transport.js:159:17
    at Set.forEach (<anonymous>)
    at gie.on (Transport.js:158:35)
    at Eoe (API.js:615:15)
    at Object.init (API.js:862:9)
    at actions.js:27:44
    at index.js:11:18
    at middleware.js:30:12
    at middleware.js:33:20
    at middleware.js:19:20
    at middleware.web.js:29:20
    at middleware.any.js:44:20
    at middleware.js:67:12
    at middleware.js:45:12
    at middleware.js:61:12
    at middleware.js:20:20
    at middleware.js:121:12
    at middleware.js:71:12
    at middleware.js:79:20
    at middleware.js:39:12
    at middleware.js:221:12
    at middleware.js:11:20
    at middleware.js:68:12
    at middleware.js:31:20
    at middleware.web.js:46:12
    at middleware.web.js:24:12
    at middleware.any.js:94:20
    at middleware.js:77:12
    at middleware.web.js:38:20
    at middleware.js:32:12
    at middleware.js:25:12
    at middleware.js:16:20
    at middleware.js:21:12
    at middleware.js:23:12
    at middleware.js:20:20
    at middleware.js:167:12
    at middleware.js:16:16
    at middleware.js:39:20
    at middleware.js:33:12
    at middleware.js:209:12
    at middleware.js:39:12
    at middleware.js:24:12
    at middleware.js:28:20
    at middleware.web.js:20:20
    at middleware.js:42:20
    at middleware.js:227:12
    at middleware.js:21:20
    at middleware.js:130:12
    at middleware.js:44:12
    at middleware.js:49:12
    at middleware.js:90:20
    at middleware.js:12:20
    at middleware.js:39:12
    at middleware.js:35:12
    at middleware.web.js:30:12
    at middleware.any.js:105:12
    at middleware.js:203:12
    at middleware.js:106:20
    at middleware.js:29:16
    at middleware.js:27:12
    at middleware.js:23:20
    at middleware.web.js:11:20
    at middleware.any.js:78:12
    at middleware.js:16:20
    at middleware.js:91:12
    at middleware.js:75:12
    at middleware.js:24:20
    at middleware.js:20:12
    at middleware.js:15:20
    at middleware.js:188:12
    at middleware.js:23:20
    at middleware.js:21:20
    at middleware.js:25:12
    at middleware.js:76:20
    at middleware.js:236:12
    at middleware.web.js:26:12
    at middleware.js:201:12
    at middleware.js:38:12
    at Object.dispatch (middleware.web.js:124:12)
    at APP.componentDidMount (BaseApp.js:100:26)
    at async APP.componentDidMount (AbstractApp.js:44:28)

---

middleware.js:154 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_navigate')
    at middleware.js:154:48

---

chrome-extension://invalid/:1          GET chrome-extension://invalid/ net::ERR_FAILED
```

The last one occurs even if the page loads correctly, so maybe it's not relevant.
[Here ](https://moodle.org/plugins/mod_jitsi) I see an user seems have a similar problem so maybe this issue could help.
Worth to mention that I'm using v2.5 plugin.
I'll be happy to provide more informations if needed.

**Comment by SergioComeron** [comment]
Hi @mattiagalati , 
thanks for open the issue. 
It's a bug in the latest versions of chrome. It is already [reported](https://community.jitsi.org/t/error-after-update-google-chrome-on-jitsi-with-iframe/109972) to Jitsi and they offer a workaround. I'm going to test how it behaves to put it in the plugin. In any case, when the screen remains black, the best way to enter is to reload the frame by clicking on the menu that appears when you click with the right mouse button.

**Comment by mattiagalati** [comment]
Hi @SergioComeron many thanks for the fast reply.
For now the refresh is perfectly suitable, I will ask my users to feedback me if they will notice any improvement: hope Jitsi could resolve this totally on their side.

**Comment by SergioComeron** [comment]
Hi, new version 3.2.4 solve this problem.
