### ISSUE TITLE
Error on first run (and not only)

### ISSUE THREAD

**Issue by Kerber0ss** [udima-university/moodle-mod_jitsi#90]
Hello, i use jitsi plugin v3.1.2  2021090100, moodle [3.11.6+ (Build: 20220318)] , theme Boost Campus.
After first open page with conference - i see blank screen, reload page - not help. But if i press at jitsi place and get context menu - Reload(one or twice or third), then all page reload and jitsi work.
In console dev tools this errors:
```
chrome-extension://invalid/:1          GET chrome-extension://invalid/ net::ERR_FAILED

middleware.js:154 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_navigate')
    at middleware.js:154:48

conference.js:3146 Uncaught (in promise) TypeError: Cannot destructure property 'id' of 'Yb(...)' as it is undefined.
    at Object.changeLocalDisplayName (conference.js:3146:17)
    at Object.display-name (API.js:178:28)
    at API.js:626:22
    at Transport.js:159:17
    at Set.forEach (<anonymous>)
    at lse.on (Transport.js:158:35)
    at yle (API.js:624:15)
    at Object.init (API.js:871:9)
    at actions.js:27:44
    at index.js:11:18
    at middleware.js:30:12
    at middleware.js:33:20
    at middleware.js:19:20
    at middleware.web.js:29:20
    at middleware.any.js:46:20
    at middleware.js:67:12
    at middleware.js:45:12
    at middleware.js:61:12
    at middleware.js:20:20
    at middleware.js:121:12
    at middleware.js:71:12
    at middleware.js:79:20
    at middleware.js:39:12
    at middleware.js:221:12
    at middleware.js:11:20
    at middleware.js:80:12
    at middleware.js:31:20
    at middleware.web.js:46:12
    at middleware.web.js:24:12
    at middleware.any.js:94:20
    at middleware.js:46:12
    at middleware.js:77:12
    at middleware.web.js:31:20
    at middleware.js:32:12
    at middleware.js:25:12
    at middleware.js:16:20
    at middleware.js:21:12
    at middleware.js:23:12
    at middleware.js:21:20
    at middleware.js:16:16
    at middleware.js:39:20
    at middleware.js:33:12
    at middleware.js:256:12
    at middleware.js:39:12
    at middleware.js:24:12
    at middleware.js:28:20
    at middleware.web.js:20:20
    at middleware.js:42:20
    at middleware.js:227:12
    at middleware.js:21:20
    at middleware.js:147:12
    at middleware.js:44:12
    at middleware.js:49:12
    at middleware.js:90:20
    at middleware.js:12:20
    at middleware.js:39:12
    at middleware.js:35:12
    at middleware.web.js:52:12
    at middleware.any.js:109:12
    at middleware.js:203:12
    at middleware.js:106:20
    at middleware.js:29:16
    at middleware.js:23:16
    at middleware.js:27:12
    at middleware.js:23:20
    at middleware.web.js:11:20
    at middleware.any.js:78:12
    at middleware.js:16:20
    at middleware.js:91:12
    at middleware.js:75:12
    at middleware.js:24:20
    at middleware.js:20:12
    at middleware.js:15:20
    at middleware.js:188:12
    at middleware.js:23:20
    at middleware.js:21:20
    at middleware.js:25:12
    at middleware.js:76:20
    at middleware.js:236:12
    at middleware.web.js:26:12
    at middleware.js:201:12
    at middleware.js:38:12
    at middleware.web.js:124:12
    at Object.dispatch (middleware.js:180:12)
    at APP.componentDidMount (BaseApp.js:100:26)
    at async APP.componentDidMount (AbstractApp.js:44:28)
```

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/9537017/162266371-837dc060-9c05-4a55-a34e-59c96ce4c2ad.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/9537017/162266435-b7ffc81f-d316-4af4-bbb4-0d08f5f7ebdd.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/9537017/162266522-bc8c7ed4-94e2-4867-b649-f95a7c2d6014.png">

About this error 

```
chrome-extension://invalid/:1          GET chrome-extension://invalid/ net::ERR_FAILED
```
I installed Jitsi extension and error is missing now.

**Comment by SergioComeron** [comment]
Hi @Kerber0ss, 
this is an error that they are having in Jitsi with chrome in the latest versions. In this forum (https://community.jitsi.org/t/error-after-update-google-chrome-on-jitsi-with-iframe/109972/3) you can see that they offer some solutions but I have tried and they have not been successful in the plugin.

**Comment by Kerber0ss** [comment]
> Hi @Kerber0ss,
> this is an error that they are having in Jitsi with chrome in the latest versions. In this forum (https://community.jitsi.org/t/error-after-update-google-chrome-on-jitsi-with-iframe/109972/3) you can see that they offer some solutions but I have tried and they have not been successful in the plugin.

Thank you, We'll wait until they fix it. Temporary solutions can be done for yourself, but not for all students and teachers

**Comment by SergioComeron** [comment]
Hi, new version 3.2.4 solve this problem.
